version: '3.8'

services:
  db:
    image: mariadb:10.9
    restart: always
    environment:
      MYSQL_DATABASE: 'crudzao'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
volumes:
  my-db: